# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         go-db-perl
version:      0.01
version_from: GO/AppHandle.pm
installdirs:  site
requires:
    Bio::Seq:                      0.0/bioperl
    Carp:                          0.0/Carp
    Data::Stag:                    0.0/Stag
    DBI:                           0.0/DBI for DbUtils::SqlWrapper
    DBIx::DBStag:                  0.06
    Digest::MD5:                   0.0/MD5
    FreezeThaw:                    0.0
    Set::Scalar:                   0.0/Scalar

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
